
#include <iostream>
using namespace std;

int main(){
cout <<"Content-type:text/html\r\n\r\n";
cout << "<!doctype html>";
cout << "<html lang=\"en\">";
cout << "    <head>";
cout << "        <!-- Required meta tags -->";
cout << "        <meta charset=\"utf-8\">";
cout << "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">";
cout << "        <link rel=\"icon\" href=\"../../img/favicon.png\" type=\"image/png\">";
cout << "        <title>Team HTML</title>";
cout << "        <!-- Bootstrap CSS -->";
cout << "        <link rel=\"stylesheet\" href=\"../../css/bootstrap.css\">";
cout << "        <link rel=\"stylesheet\" href=\"../../vendors/linericon/style.css\">";
cout << "        <link rel=\"stylesheet\" href=\"../../css/font-awesome.min.css\">";
cout << "        <link rel=\"stylesheet\" href=\"../../vendors/lightbox/simpleLightbox.css\">";
cout << "        <link rel=\"stylesheet\" href=\"../../vendors/nice-select/css/nice-select.css\">";
cout << "        <!-- main css -->";
cout << "        <link rel=\"stylesheet\" href=\"../../css/style.css\">";
cout << "        <link rel=\"stylesheet\" href=\"../../css/responsive.css\">";
cout << "    </head>";
cout << "    <body>";
cout << "        ";
cout << "        <!--================ Start Header Menu Area =================-->";
cout << "        <header class=\"header_area\">";
cout << "        <div class=\"main_menu\">";
cout << "            <div class=\"container\">";
cout << "                <nav class=\"navbar navbar-expand-lg navbar-light\">";
cout << "                    <div class=\"container\" style=\"height:60px\">";
cout << "                        <a class=\"navbar-brand logo_h\" href=\"../../index.html\"><h3 style=\"color:white\">Team HTML<h3></a>";
cout << "                        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
cout << "                            <span class=\"icon-bar\"></span>";
cout << "                            <span class=\"icon-bar\"></span>";
cout << "                            <span class=\"icon-bar\"></span>";
cout << "                        </button>";
cout << "                        <div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">";
cout << "                            <ul class=\"nav navbar-nav menu_nav ml-auto\" style=\"height:80px\">";
cout << "                                <li class=\"nav-item \"><a class=\"nav-link\" href=\"../../index.html\">Home</a></li> ";
cout << "                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"../../profile.html\">My Profile</a></li> ";
cout << "                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"../../settings.html\">Settings</a></li> ";
cout << "                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"../../login.html\">Log Out</a>";
cout << "                                ";
cout << "                               ";
cout << "                            </ul>";
cout << "                        </div> ";
cout << "                    </div>";
cout << "                </nav>";
cout << "            </div>";
cout << "        </div>";
cout << "    </header>";
cout << "        <!--================ End Header Menu Area =================-->";
cout << "            ";
cout << "        <!--================ Home Banner Area =================-->";
cout << "        <section class=\"banner_area\">";
cout << "            <div class=\"banner_inner d-flex align-items-center\">";
cout << "                <div class=\"overlay bg-parallax\" data-stellar-ratio=\"0.9\" data-stellar-vertical-offset=\"0\" data-background=\"\"></div>";
cout << "                <div class=\"container\">";
cout << "                    <div class=\"banner_content text-center single_sidebar_widget popular_post_widget\">";
cout << "                        <h2>Great Time for Sharing</h2>";
cout << "                        <p>Let others know about your event!</p>";
cout << "                        <span class=\"input-group-btn\"><br>";
cout << "                        <a href= \"../../create_post.html\"><button class=\"btn btn-default\" type=\"button\">Create a post</button></a>";
cout << "                    </span>";
cout << "                    </div>";
cout << "                </div>";
cout << "            </div>";
cout << "        </section>";
cout << "        <!--================ End Home Banner Area =================-->";
cout << "        ";
cout << "        <!--================ Cities Area =================-->";
cout << "        <section class=\"blog_categorie_area\">";
cout << "            <div class=\"container\">";
cout << "                <div class=\"row\">";
cout << "                    <div class=\"col-lg-4\">";
cout << "                        <div class=\"categories_post\">";
cout << "                            <img src=\"https://www.wapititravel.com/blog/wp-content/uploads/2019/07/Seoul_South_Korea.jpg.webp\" alt=\"post\">";
cout << "                            <div class=\"categories_details\">";
cout << "                                <div class=\"categories_text\">";
cout << "                                    <a href=\"#\"><h5>Seoul</h5></a>";
cout << "                                    ";
cout << "                                </div>";
cout << "                            </div>";
cout << "                        </div>";
cout << "                    </div>";
cout << "                    <div class=\"col-lg-4\">";
cout << "                        <div class=\"categories_post\">";
cout << "                            <img src=\"https://www.costacruises.com/content/dam/costa/inventory-assets/ports/PUS/pus-busan-port-1.jpg.image.750.563.low.jpg\" alt=\"post\">";
cout << "                            <div class=\"categories_details\">";
cout << "                                <div class=\"categories_text\">";
cout << "                                    <a href=\"#\"><h5>Busan</h5></a>";
cout << "                                </div>";
cout << "                            </div>";
cout << "                        </div>";
cout << "                    </div>";
cout << "                    <div class=\"col-lg-4\">";
cout << "                        <div class=\"categories_post\">";
cout << "                            <img src=\"https://www.lottehotelmagazine.com/resources/c90d48a5-ec3d-46c9-aacd-fae6011accc0_img_art_daejeon_detail01.jpg\" alt=\"post\">";
cout << "                            <div class=\"categories_details\">";
cout << "                                <div class=\"categories_text\">";
cout << "                                    <a href=\"#\"><h5>Daejeon</h5></a>";
cout << "                                    ";
cout << "                                </div>";
cout << "                            </div>";
cout << "                        </div>";
cout << "                    </div>";
cout << "                </div>";
cout << "            </div>";
cout << "        </section>";
cout << "        <!--================ Cities Area =================-->";
cout << "        ";
cout << "        <!--================ Events Area =================-->";
cout << "        <section class=\"blog_area\">";
cout << "            <div class=\"container\">";
cout << "                <div class=\"row\">";
cout << "                    <div class=\"col-lg-8\">";
cout << "                        <div class=\"blog_left_sidebar\">";
cout << "                            <article class=\"row blog_item\">";
cout << "                               <div class=\"col-md-3\">";
cout << "                                   <div class=\"blog_info text-right\">";
cout << "                                        <div class=\"post_tag\">";
cout << "                                            <a >Seoul</a>";
cout << "                                            <a >Anam,</a>";
cout << "                                            <a >Korea University</a>";
cout << "                                           ";
cout << "                                        </div>";
cout << "                                        <ul class=\"blog_meta list\">";
cout << "                                            <li><a href=\"../../profile.html\">John Doe<i class=\"lnr lnr-user\"></i></a></li>";
cout << "                                            <li></li><li><a>29.04.2021<i class=\"lnr lnr-calendar-full\"></i></a></li>";
cout << "                                            <li><a>10,000 Views<i class=\"lnr lnr-eye\"></i></a></li>";
cout << "                                            ";
cout << "                                        </ul>";
cout << "                                    </div>";
cout << "                               </div>";
cout << "                                <div class=\"col-md-9\">";
cout << "                                    <div class=\"blog_post\">";
cout << "                                        <img src=\"../../images/announcement1.jpg\" alt=\"\">";
cout << "                                        <div class=\"blog_details\">";
cout << "                                            <a href=\"#\"><h2>Open!</h2></a>";
cout << "                                            <p>Greetings to all exchange students all over South Korea! This project started with the aim of meeting and connecting people who currently study here. You can use this web-app for posting announcements or looking for some events where international students are gathering all together. Have a good stay!</p>";
cout << "                                            ";
cout << "                                        </div>";
cout << "                                    </div>";
cout << "                                </div>";
cout << "                            </article>";
cout << "                            <article class=\"row blog_item\">";
cout << "                               <div class=\"col-md-3\">";
cout << "                                   <div class=\"blog_info text-right\">";
cout << "                                        <div class=\"post_tag\">";
cout << "                                            <a>Seoul,</a>";
cout << "                                            <a>Some Random Forest</a>";
cout << "                                        </div>";
cout << "                                        <ul class=\"blog_meta list\">";
cout << "                                            <li><a href=\"../../profile.html\">Jane Doe<i class=\"lnr lnr-user\"></i></a></li>";
cout << "                                            <li><a>29.04.2021<i class=\"lnr lnr-calendar-full\"></i></a></li>";
cout << "                                            <li><a>120,000 Views<i class=\"lnr lnr-eye\"></i></a></li>";
cout << "                                        </ul>";
cout << "                                    </div>";
cout << "                               </div>";
cout << "                                <div class=\"col-md-9\">";
cout << "                                    <div class=\"blog_post\">";
cout << "                                        <img src=\"../../img/blog/main-blog/m-blog-2.jpg\" alt=\"\">";
cout << "                                        <div class=\"blog_details\">";
cout << "                                            <a href=\"#\"><h2>Some Title</h2></a>";
cout << "                                            <p>Some Text Over Here. This is the example of the announcement board card snippet. All the announcements will have this style.</p>";
cout << "                                            ";
cout << "                                        </div>";
cout << "                                    </div>";
cout << "                                </div>";
cout << "                            </article>";
cout << "                            <article class=\"row blog_item\">";
cout << "                               <div class=\"col-md-3\">";
cout << "                                   <div class=\"blog_info text-right\">";
cout << "                                        <div class=\"post_tag\">";
cout << "                                            <a>Seoul,</a>";
cout << "                                            <a>Some Random Pary</a>";
cout << "                                        </div>";
cout << "                                        <ul class=\"blog_meta list\">";
cout << "                                            <li><a href=\"../../profile.html\">Jane Doe<i class=\"lnr lnr-user\"></i></a></li>";
cout << "                                            <li><a>29.04.2021<i class=\"lnr lnr-calendar-full\"></i></a></li>";
cout << "                                            <li><a>120,000 Views<i class=\"lnr lnr-eye\"></i></a></li>";
cout << "                                        </ul>";
cout << "                                    </div>";
cout << "                               </div>";
cout << "                                <div class=\"col-md-9\">";
cout << "                                    <div class=\"blog_post\">";
cout << "                                        <img src=\"https://orlandoweeklytickets.com/imager/b/original/102008998/0349/NJA_7395.jpg\" alt=\"\">";
cout << "                                        <div class=\"blog_details\">";
cout << "                                            <a href=\"#\"><h2>Some Title</h2></a>";
cout << "                                            <p>Some Text Over Here. This is the example of the announcement board card snippet. All the announcements will have this style.</p>";
cout << "                                            ";
cout << "                                        </div>";
cout << "                                    </div>";
cout << "                                </div>";
cout << "                            </article>";
cout << "";
cout << "";
cout << "                            <article class=\"row blog_item\">";
cout << "                               <div class=\"col-md-3\">";
cout << "                                   <div class=\"blog_info text-right\">";
cout << "                                        <div class=\"post_tag\">";
cout << "                                            <a>Seoul,</a>";
cout << "                                            <a>Some Random Place</a>";
cout << "                                        </div>";
cout << "                                        <ul class=\"blog_meta list\">";
cout << "                                            <li><a href=\"../../profile.html\">Jane Doe<i class=\"lnr lnr-user\"></i></a></li>";
cout << "                                            <li><a>29.04.2021<i class=\"lnr lnr-calendar-full\"></i></a></li>";
cout << "                                            <li><a>120,000 Views<i class=\"lnr lnr-eye\"></i></a></li>";
cout << "                                        </ul>";
cout << "                                    </div>";
cout << "                               </div>";
cout << "                                <div class=\"col-md-9\">";
cout << "                                    <div class=\"blog_post\">";
cout << "                                        <img src=\"https://teanabroad.org/wp-content/uploads/2015/12/Korea-University-Media-1-1.jpg\" alt=\"\">";
cout << "                                        <div class=\"blog_details\">";
cout << "                                            <a href=\"#\"><h2>Some Title</h2></a>";
cout << "                                            <p>Some Text Over Here. This is the example of the announcement board card snippet. All the announcements will have this style.</p>";
cout << "                                            ";
cout << "                                        </div>";
cout << "                                    </div>";
cout << "                                </div>";
cout << "                            </article>";
cout << "";
cout << "";
cout << "                            ";
cout << "                            <nav class=\"blog-pagination justify-content-center d-flex\">";
cout << "		                        <ul class=\"pagination\">";
cout << "		                            <li class=\"page-item\">";
cout << "		                                <a href=\"#\" class=\"page-link\" aria-label=\"Previous\">";
cout << "		                                    <span aria-hidden=\"true\">";
cout << "		                                        <span class=\"lnr lnr-chevron-left\"></span>";
cout << "		                                    </span>";
cout << "		                                </a>";
cout << "		                            </li>";
cout << "		                            <li class=\"page-item\"><a href=\"#\" class=\"page-link\">01</a></li>";
cout << "		                            <li class=\"page-item active\"><a href=\"#\" class=\"page-link\">02</a></li>";
cout << "		                            <li class=\"page-item\"><a href=\"#\" class=\"page-link\">03</a></li>";
cout << "		                            <li class=\"page-item\"><a href=\"#\" class=\"page-link\">04</a></li>";
cout << "		                            <li class=\"page-item\"><a href=\"#\" class=\"page-link\">05</a></li>";
cout << "		                            <li class=\"page-item\">";
cout << "		                                <a href=\"#\" class=\"page-link\" aria-label=\"Next\">";
cout << "		                                    <span aria-hidden=\"true\">";
cout << "		                                        <span class=\"lnr lnr-chevron-right\"></span>";
cout << "		                                    </span>";
cout << "		                                </a>";
cout << "		                            </li>";
cout << "		                        </ul>";
cout << "		                    </nav>";
cout << "                        </div>";
cout << "                    </div>";
cout << "                    <div class=\"col-lg-4\">";
cout << "                        <div class=\"blog_right_sidebar\">";
cout << "                           <aside class=\"single_sidebar_widget search_widget\">";
cout << "                                <div class=\"input-group\">";
cout << "                                    <input type=\"text\" class=\"form-control\" placeholder=\"Search Posts\">";
cout << "                                    <span class=\"input-group-btn\">";
cout << "                                        <button class=\"btn btn-default\" type=\"button\"><i class=\"lnr lnr-magnifier\"></i></button>";
cout << "                                    </span>";
cout << "                                </div><input-group>";
cout << "                                <div class=\"br\"></div>";
cout << "                            </aside> ";
cout << "                            ";
cout << "                            <aside class=\"single_sidebar_widget popular_post_widget\">";
cout << "                                ";
cout << "                                <div class=\"media post_item\">";
cout << "                                    <img src=\"../../img/blog/popular-post/post1.jpg\" alt=\"post\">";
cout << "                                    <div class=\"media-body\">";
cout << "                                        <a href=\"#\"><h3>Advertisement</h3></a>";
cout << "                                    <a href=\"#\"><p>Link</p></a>";
cout << "                                    </div>";
cout << "                                </div>";
cout << "                                <div class=\"media post_item\">";
cout << "                                    <img src=\"../../img/blog/popular-post/post2.jpg\" alt=\"post\">";
cout << "                                    <div class=\"media-body\">";
cout << "                                        <a href=\"#\"><h3>Advertisement</h3></a>";
cout << "                                    <a href=\"#\"><p>Link</p></a>";
cout << "                                    </div>";
cout << "                                </div>";
cout << "                                <div class=\"media post_item\">";
cout << "                                    <img src=\"../../img/blog/popular-post/post3.jpg\" alt=\"post\">";
cout << "                                    <div class=\"media-body\">";
cout << "                                        <a href=\"#\"><h3>Advertisement</h3></a>";
cout << "                                    <a href=\"#\"><p>Link</p></a>";
cout << "                                    </div>";
cout << "                                </div>";
cout << "                                <div class=\"media post_item\">";
cout << "                                    Text Over Here. This is the example of the announcement board card snippet. All the announcements will have this style. <img src=\"../../img/blog/popular-post/post4.jpg\" alt=\"post\">";
cout << "                                    <div class=\"media-body\">";
cout << "                                        <a href=\"#\"><h3>Advertisement</h3></a>";
cout << "                                    <a href=\"#\"><p>Link</p></a>";
cout << "                                    </div>";
cout << "                                </div>";
cout << "                                <div class=\"br\"></div>";
cout << "                            </aside>";
cout << "                            ";
cout << "                        </div>";
cout << "                    </div>";
cout << "                </div>";
cout << "            </div>";
cout << "        </section>";
cout << "        <!--================Events Area =================-->";
cout << "        ";
cout << "         <!--================ Start footer Area  =================-->	";
cout << "    <footer>";
cout << "";
cout << "";
cout << "        <div class=\"footer-bottom\">";
cout << "            <div class=\"container\">";
cout << "                <div class=\"row d-flex\">";
cout << "                    <p class=\"col-lg-12 footer-text text-center\">";
cout << "                        ";
cout << "Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved |Done by <b>Team HTML</b>";
cout << "</p>";
cout << "                </div>";
cout << "            </div>";
cout << "        </div>";
cout << "    </footer>";
cout << "        <!--================ End footer Area  =================--> ";
cout << "        ";
cout << "        ";
cout << "        ";
cout << "        ";
cout << "        <!-- Optional JavaScript -->";
cout << "        <!-- jQuery first, then Popper.js, then Bootstrap JS -->";
cout << "        <script src=\"../../js/jquery-3.2.1.min.js\"></script>";
cout << "        <script src=\"../../js/popper.js\"></script>";
cout << "        <script src=\"../../js/bootstrap.min.js\"></script>";
cout << "        <script src=\"../../js/stellar.js\"></script>";
cout << "        <script src=\"../../vendors/lightbox/simpleLightbox.min.js\"></script>";
cout << "        <script src=\"../../vendors/nice-select/js/jquery.nice-select.min.js\"></script>";
cout << "        <script src=\"../../js/jquery.ajaxchimp.min.js\"></script>";
cout << "        <script src=\"../../js/mail-script.js\"></script>";
cout << "        <script src=\"../../js/theme.js\"></script>";
cout << "    </body>";
cout << "</html>";
return 0;
}
